# Generated by Django 5.2.1 on 2025-05-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_task_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskDRF',
        ),
    ]
